import org.apache.tools.ant.filters.ReplaceTokens

plugins {
    id "java-library"
    id "com.gradleup.shadow" version "8.3.9"
}

dependencies {
    implementation project(":api")
}

processResources {
    filter ReplaceTokens, tokens: [
            "version": version
    ]
}

shadowJar {
    archiveBaseName.set("MenuInv")
    archiveClassifier.set("")
    archiveVersion.set("")
}

artifacts {
    archives shadowJar
}
